# Generated by Django 4.1.5 on 2023-01-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="unit_price",
        ),
    ]
