# Generated by Django 4.1.5 on 2023-01-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_store", "0004_customer_store_custo_last_na_e6a359_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="customer",
            name="store_custo_last_na_e6a359_idx",
        ),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(
                fields=["first_name", "last_name"],
                name="my_store_cu_first_n_9cdfbb_idx",
            ),
        ),
        migrations.AlterModelTable(
            name="customer",
            table="my_store_customers",
        ),
    ]
